### ISSUE TITLE
Joy is not very beginner friendly

### ISSUE THREAD

**Issue by anandology** [fossunited/joy#13]
I've been trying to teach the joy of programming course to some students. While they appreciate that the new library is more expressive, most of them feel that the new API is hard for beginners than it's previous version. 

### Case Variations

Beginners easily make mistakes with cases.  Having to type some in TitleCase is confusing. Also, couple of students are leraning this on mobile phone and that is even more difficult.

Also, the primitive shapes are in TitleCase and the user defined shapes will usually be in lower case. That is inconsistent. 

### Using Point

Forcing to use Point from the beginning is confusing for beginners. It adds an additional layer of nesting in calling these functions.

```
c = Circle(center=Point(x=100, y=100), radius=50)

c = Circle(x=100, y=100, radius=50)
```

Also, using Point makes it hard for them to write functions that require drawing shapes with different center. 

```
def three_circles(center, radius):
    c1 = Circle(center=center, radius=radius)
    c2 = Circle(center=Point(x=center.x-2*radius, y=center.y), radius=radius)
    c3 = Circle(center=Point(x=center.x+2*radius, y=center.y), radius=radius)
    return c1 + c2 + c3

def three_circles(x, y, r):
    c1 = Circle(x=x, y=y, radius=r)
    c2 = Circle(x=x-2*r, y=y, radius=r)
    c3 = Circle(x=x+2*r, y=y, radius=r)
    return c1 + c2 + c3

# or even

def three_circles(x, y, r):
     x1 = x
     x2 = x - 2 * r
     x3 = x + 2* r
    c1 = Circle(x=x1, y=y, radius=r)
    c2 = Circle(x=x2, y=y, radius=r)
    c3 = Circle(x=x3, y=y, radius=r)
    return c1 + c2 + c3
```

I agree that the current version works very well with transformations, but they are introduced much later in the course.

### Long Argument Names

The long arguments names are inconvenient. They are easy to understand in the beginning, but repeated use is painful. 

```
s1 = Circle(x=10, y=20, radius=30)
s2 = Rectangle(x=10, y=20, width=30, height=40)
---
s1 = Circle(x=10, y=20, r=30)
s2 = Rectangle(x=10, y=20, w=30, h=40)
```

## Proposed API

- all functions are lowercase
- short argument names
- x/y instead of point
- point will still be there and used for polygon etc and used in the internal representations

```
c = circle()
c = circle(r=100)
c = circle(x=10, y=20, r=100)
c = circle(10, 20, 100)

r = rectangle()
r = rectangle(w=100, h=200)
r = rectangle(x=20, y=30, w=100, h=200)
r = rectangle(20, 30, 100, 200)

z = line()
z = line(x1=10, y1=20, x2=100, y2=120)

s = polygon([
    point(0, 0),
    point(100, 0),
    point(0, 100)
])

line() | repeat(4, rotate(10))
rectangle() | repeat(36, rotate(10) | scale(0.9))

circle() | translate(x=10, y=20)
circle() | translate(10, 20)
circle() | translate(x=10)
circle() | translate(y=20)

circle() | scale(1.5)   # scale both x and y
circle() | scale(x=1.5) # scale only x
circle() | Scale(y=1.2) # scale only y
```

@amitkaps what do you think?

**Comment by amitkaps** [comment]
Makes sense. If you dropping the concept of Point in the external api, then the following can be simplified also (though you lose keyword args)

```
z = line((10, 20), (100, 120))
p = polygon([(0,0), (2,4), (3, 4)
```

**Comment by anandology** [comment]
The idea is to remove point from the view of the beginners. The `point` will still be available in the library and also in the public API, but only in the advanced usage.

```
polygon([
    point(0, 0),
    point(2, 4),
    point(3, 4)
])

rectangle() | rotate(45, anchor=point(10, 20))
```

**Comment by anandology** [comment]
done.
