### ISSUE TITLE
Shape is changed when saving as draft

### ISSUE THREAD

**Issue by rohittp0** [fossunited/joy#24]
### Expected
![Expected](https://media.discordapp.net/attachments/877571907837366333/877572181146599464/run.png?width=1009&height=435)
### Shown
![Shown](https://media.discordapp.net/attachments/877571907837366333/877572084543406170/draft.png?width=1002&height=435)

### Effected Submissions

1. 5b69d8c39b

**Comment by anandology** [comment]
Fixed now.
