### ISSUE TITLE
Add Ellipse Shape

### ISSUE THREAD

**Issue by anandology** [fossunited/joy#3]
## The API

I think it is better to specify width and height of the ellipse, just like the rectangle. Using `rx` an `ry` as in SVG doesn't look that elegant. 

```
e = Ellipse()
e = Ellipse(width=100, height=200)
e = Ellipse(center=Point(10, 20), width=100, height=200)
```

Going by the same argument, we should be using the diameter for the circle, not radius.  @amitkaps what do you think?

## Reference

<https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse>

**Comment by amitkaps** [comment]
From a compass analogy, radius is easier to understand. From alignment with Ellipse syntax, width = height = diameter is better. 

Either is fine. You should pick based on how you want teach it for the moment and your objectives on syntactic simplicity.
