### ISSUE TITLE
Bug in rendering repeat

### ISSUE THREAD

**Issue by anandology** [fossunited/joy#34]
The following code is producing wrong output.

```
a = ellipse() 
b = a | repeat(2, rotate(90))
a1 = a | scale(x=0.5) | translate(x=75)
b1 = b | scale(x=0.5) | translate(x=-75)
show(a1+b1)
```

This generates the following output, which is incorrect.

![bug-1](https://user-images.githubusercontent.com/7569/147640596-5804be34-8698-4a16-964a-368cebcd0a9b.png)

If you use another `ellipse()` to create `b` instead of reusing `a`, it gives the correct output.

```
a = ellipse() 
b = ellipse() | repeat(2, rotate(90))
a1 = a | scale(x=0.5) | translate(x=75)
b1 = b | scale(x=0.5) | translate(x=-75)
show(a1+b1)
```

Correct output:

![bug-2](https://user-images.githubusercontent.com/7569/147640605-b0a99e62-c1b9-4360-9084-604d4e7383ca.png)

## Notes

Looks like there is some issue with the way references are handled.

**Comment by tusharsadhwani** [comment]
I wonder if it's the cloning logic. I'll look into this

**Comment by anandology** [comment]
This is the generated svg for the initial code.  As you can see the ellipse with id `shape4518245904` is defined twice. Which shouldn't be the case. 

```
<svg width="300" height="300" viewBox="-150 -150 300 300" fill="none" stroke="black" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g transform="scale(1 -1)">
  <g>
    <g>
      <ellipse cx="0" cy="0" rx="100.0" ry="50.0" id="shape4518245904" transform="translate(75 0) scale(0.5 1)" />
      <g transform="translate(-75 0) scale(0.5 1)">
        <defs>
          <ellipse cx="0" cy="0" rx="100.0" ry="50.0" id="shape4518245904" />
        </defs>
        <g>
          <use xlink:href="#shape4518245904" />
          <use xlink:href="#shape4518245904" transform="rotate(90)" />
        </g>
      </g>
    </g>
  </g>
</g>
</svg>
```

**Comment by anandology** [comment]
> I wonder if it's the cloning logic. I'll look into this

Yes, you are right. The issue is with the cloning logic. It was sharing the attrs with the cloned node and that was causing the issue. 

Sorry, I couldn't wait for you to fix this as I blocked on this fix.

**Comment by tusharsadhwani** [comment]
No worries, I was wondering if we need to deep copy when I originally saw that code. Turns out you do :)
