### ISSUE TITLE
Add Square shape

### ISSUE THREAD

**Issue by anandology** [fossunited/joy#7]
Add `Square` shape. 

Just like we have `Ellipse` and `Circle`. We could have `Rectangle` and `Square`.

## The API

```
s = Square()
s = Square(size=200)
s = Square(center=Point(x=100, y=100), size=200)
```

## Attributes

The square object will have the following attributes:

- center
- size
- width
- height

The value of `height` and `width` attributes would be same as the `size`.

**Comment by anandology** [comment]
@amitkaps what do you think?

**Comment by amitkaps** [comment]
`size` normally refers to `area`. Maybe `length` is more idiomatic?

**Comment by anandology** [comment]
Not doing this. We leave that as exercise for students.
